name: chemml
channels:
  - conda-forge
  - rdkit
dependencies:
  - python=3.5
  - numpy=1.13.1
  - pandas=0.20.3
  - scikit-learn=0.19.1
  - tensorflow=1.4.1
  - keras=2.1.2
  - rdkit
  - babel=2.3.4
  - deap=1.2.2
  - matplotlib
  - lxml
  - jupyter
  - ipython
  - ipywidgets
  - graphviz
  - pip:
    - graphviz